[package]
name = "bookmarks-data"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
fuzzy-matcher.workspace = true
itertools.workspace = true
serde.workspace = true
toml.workspace = true
